spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: taylor
    password: taylor
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.bank.system.model
  config-location: classpath:mybatis/mybatis-config.xml